GET http://127.0.0.1:8000/api/producto?q=a&limit=2&page=1
Accept: application/json
Authorization: Bearer 86|QKh9UCiG6Vc5Hf2zjDjdCK8hipVkK6VEslxHfiPT5a2d7da4

### guardar producto

POST http://127.0.0.1:8000/api/producto
Accept: application/json
Authorization: Bearer 86|QKh9UCiG6Vc5Hf2zjDjdCK8hipVkK6VEslxHfiPT5a2d7da4
Content-Type: application/json 

{
    "nombre":"parlantes",
    "stock":"20",
    "precio":"250",
    "descripcion": "electronicos",
    "estado": true,
    "categoria_id": 1

}